name: Semantic Release
on:
  workflow_dispatch:
  push:
    branches:
      - github_actions

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout repository at workflow sha
        uses: actions/checkout@v4
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel
      - name: Compile | Linux
        run: |
          make
          ls bin
        if: runner.os == 'Linux'
      - run: '${{ runner.temp }}\webimage_extracted\bootstrapper.exe -s --action install --components=intel.oneapi.win.ifort-compiler:intel.oneapi.win.cpp-compiler --eula=accept -p=NEED_VS2017_INTEGRATION=0 -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=1 --log-dir=${{ runner.temp }}'
        shell: cmd
        if: runner.os == 'Windows'
      - name: Compile | Windows
        run: |
          devenv.com Nemoh.sln /build "Release|x64"
          ls
        if: runner.os == 'Windows'
      - uses: actions/upload-artifact@v4
        with:
          name: UpgradeLog
          path: UpgradeLog.htm
        if: runner.os == 'Windows'
