name: Semantic Release
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Setup | Checkout repository at workflow sha
        uses: actions/checkout@v4
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel
      - run: |
          make
